movie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieapp/urls.py
from django.urls import path
from movieapp import views
app_name = 'movieapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>', views.detail, name='detail'),
    path('add/', views.add_movie, name='add'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete')
]

movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=300)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from movieapp.forms import MovieForm
from movieapp.models import Movie


# Create your views here.

def index(request):
    movie = Movie.objects.all()
    context = {
        "movie_list": movie
    }
    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, 'details.html', {'movie': movie})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()

    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})

def delete(request,id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')

    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}

    <div class="container">
        <div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset>
                    <legend><h2>Add Movies Here</h2></legend>
                    <p>
                        <label>Movie Name : </label>
                        <input type="text" name="name" placeholder="Movie Name">
                    </p>
                    <p>
                        <label>Movie description : </label>
                        <input type="text" name="desc" placeholder="Movie description">
                    </p>
                    <p>
                        <label>Release Year : </label>
                        <input type="text" name="year" placeholder="Year">
                    </p>
                    <p>
                        <label>Movie Name : </label>
                        <input type="file" name="img">
                    </p>
                    <p>
                        <input type="submit" value="Add Movie">
                    </p>
                </fieldset>
            </form>
        </div>
    </div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie-List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'movieapp:add' %}">
           Your Movie List
        </a>
      </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

<!--bg-body-tertiary-->

templates/delete.html
{% extends 'base.html' %}
{% block body %}

  <form action="" method="post">
    {% csrf_token %}
    <p>
      <input type="checkbox" required>
      <label>Are you sure that you want to delete this movie?</label>
    </p>
    <p><input type="submit" value="Yes Delete"></p>
  </form>

{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
            <img src="{{movie.img.url}}" alt="{{movie.name}}" width="300" height="400">
        </div>
        <div class="col-md-6">
            <h3 class="ddd">{{movie.name}}</h3>
            <h5 class="ddd">({{movie.year}})</h5>
            <p class="ddd">{{movie.desc}}</p>
            <p class="ddd"><a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a></p>
            <p class="ddd"><a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a></p>
        </div>
        </div>
    </div>

{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}

     <div class="container">
         <form action="" method="post" enctype="multipart/form-data">
             {% csrf_token %}
             {{form.as_p}}
             <input type="submit" value="Submit Changes">
         </form>
     </div>

{%  endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            {% for i in movie_list %}
                <div class="col-md-3">
                    <div class="card">
                      <img src="{{i.img.url}}" class="card-img-top" alt={{i.name}} height="300">
                      <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <p class="card-text">({{i.year}})</p>
                        <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View Details</a>
                      </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}